### ISSUE TITLE
Terraria.exe

### ISSUE THREAD

**Issue by fortunez** [Deathly/TerrariaAPI#22]
When i modify terraria it gives me an exception "Terraria.exe has thrown an exception" ? it used to work, it works without editing it, i used my own source,

System.TypeInitializationException was unhandled
  Message=The type initializer for 'Terraria.Main' threw an exception.
  Source=WindowsGame3
  TypeName=Terraria.Main
  StackTrace:
       at Terraria.Main..ctor()
       at Terraria.Program.Main(String[] args) in C:\Users\Mel\Desktop\C# stuffs\Terraria Clean Source\WindowsGame3\WindowsGame3\WindowsGame3\Program.cs:line 9
  InnerException: System.NullReferenceException
       Message=Object reference not set to an instance of an object.
       Source=WindowsGame3
       StackTrace:
            at Terraria.Item.SetDefaults(String ItemName) in C:\Users\Mel\Desktop\C# stuffs\Terraria Clean Source\WindowsGame3\WindowsGame3\WindowsGame3\Item.cs:line 456
            at Terraria.Player..ctor() in C:\Users\Mel\Desktop\C# stuffs\Terraria Clean Source\WindowsGame3\WindowsGame3\WindowsGame3\Player.cs:line 219
            at Terraria.Main..cctor() in C:\Users\Mel\Desktop\C# stuffs\Terraria Clean Source\WindowsGame3\WindowsGame3\WindowsGame3\Main.cs:line 70
       InnerException: 

sorry .. im a noob xD

**Comment by AlbinoDrought** [comment]
Try using this source, it has had all the errors fixed and the modclass/hooks added in.
http://www.mediafire.com/?6zyrb33ybqx1v5y

**Comment by blucat** [comment]
Make sure you have all the system requirements to run terraria then try it again. If that doesn't work, it's possible you've broken the call for one of the system dlls like user32. That error comes up when trying to run terraria server with mono. Will post details on running the server in osx once I figure it out.

**Comment by fortunez** [comment]
I know what happend Scorch has the same problem, you cant change the default stuff you get when you spawn you're character.

**Comment by Scorch-** [comment]
I actually fixed that in my newest update if you want to see how I did it.
